server:
  port: 8088

spring:
  application:
    name: notification-service
  datasource:
    url: jdbc:mysql://mysql:3306/skillsync_notifications?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
  rabbitmq:
    host: rabbitmq
    port: 5672
    username: guest
    password: guest

rabbitmq:
  exchange: skillsync.exchange
  queue:
    session: skillsync.session.queue

springdoc:
  api-docs:
    path: /notifications/v3/api-docs
